# 126 SMTP
spring.mail.host=smtp.126.com
spring.mail.port=465
spring.mail.username=a13223007172@126.com
spring.mail.password=UJnum37usuAZ8fw2

# 465 ? SSL
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

# ?????????????
patient.emailVerification.from=a13223007172@126.com

# ??????????????????????
patient.emailVerification.realSendEnabled=true