server.port=8082

spring.application.name=PatientService

# Use H2 in-memory DB for dev/testing
spring.datasource.url=jdbc:h2:mem:patientdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Enable Spring Boot automatic SQL initialization and disable DatabaseInitializer by default
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.sql.init.schema-locations=classpath:schema-dev.sql
spring.sql.init.data-locations=classpath:data-dev.sql

app.db.init=false

# keep jpa show sql for debugging
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.root=info
app.debug=true
