-- schema-dev.sql: minimal tables needed for waiting feature

CREATE TABLE IF NOT EXISTS doc_schedule_record (
  id VARCHAR(64) PRIMARY KEY,
  doctor_id VARCHAR(64),
  schedule_date DATE,
  left_source_count INT
);

CREATE TABLE IF NOT EXISTS waiting_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id VARCHAR(64) NOT NULL,
  sch_id VARCHAR(64) NOT NULL,
  apply_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(32),
  registration_id VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS registration (
  id VARCHAR(64) PRIMARY KEY,
  patient_id VARCHAR(64),
  sch_id VARCHAR(64),
  status VARCHAR(32)
);

-- Ensure our test schedule exists when using H2 (idempotent)
MERGE INTO doc_schedule_record (id, doctor_id, schedule_date, left_source_count) KEY(id) VALUES ('SCH_TEST_1', 'DOC_TEST_1', CURRENT_DATE, 0);

-- ------------------------------------------------------------------
-- Add tables expected by mappers but missing in the minimal schema
-- ------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS register_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id VARCHAR(64),
  sch_id VARCHAR(64),
  register_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS patient (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128)
);

CREATE TABLE IF NOT EXISTS patient_extra_apply (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT,
  department_id BIGINT,
  doctor_id BIGINT,
  appointment_date DATE,
  reason VARCHAR(512),
  status VARCHAR(32),
  locked BOOLEAN,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  reject_reason VARCHAR(512)
);
